import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import type { ProjectMemory } from './memory.js';

/**
 * Generate usage instructions for agents to use prose
 */
export function generateInstructions(): string {
    return `### 🧠 Semantic Memory & Search
This project uses \`prose\` to maintain a cross-session semantic memory of decisions, insights, and story beats.

- **Semantic Search**: If you're unsure about a past decision or need context on a feature, run:
  \`\`\`bash
  prose search "your question or keywords"
  \`\`\`
- **Project Status**: To see a summary of recent sessions and evolved memory, run:
  \`\`\`bash
  prose status
  \`\`\`
- **View Chronicles**: Run \`prose serve\` to browse the interactive development timeline in your browser.
`;
}

/**
 * Ensure a CLAUDE.md.template exists, creating it from CLAUDE.md if necessary
 */
export function ensureTemplate(rootPath: string): void {
    const templatePath = join(rootPath, 'CLAUDE.md.template');
    const targetPath = join(rootPath, 'CLAUDE.md');

    if (existsSync(templatePath)) {
        console.log(`ℹ️  CLAUDE.md.template already exists`);
        return;
    }

    let baseContent = '';
    if (existsSync(targetPath)) {
        baseContent = readFileSync(targetPath, 'utf-8');
    } else {
        baseContent = '# Project Guide\n\nThis is a standard guide for agents.';
    }

    // Check if it already has tags
    if (baseContent.includes('{{PROSE_SUMMARY}}')) {
        console.log(`ℹ️  CLAUDE.md already contains prose tags, using as basis for template`);
    } else {
        baseContent += `\n\n## 🧬 Project Consciousness\n{{PROSE_SUMMARY}}\n\n### Decisions\n{{PROSE_DECISIONS}}\n\n### Instructions & Usage\n{{PROSE_INSTRUCTIONS}}\n\n### Active Gotchas\n{{PROSE_GOTCHAS}}\n`;
    }

    writeFileSync(templatePath, baseContent);
    console.log(`✅ Created CLAUDE.md.template from existing CLAUDE.md`);
}

/**
 * Inject project memory into CLAUDE.md if a template exists
 */
export function injectMemory(rootPath: string, memory: ProjectMemory): void {
    const templatePath = join(rootPath, 'CLAUDE.md.template');
    const targetPath = join(rootPath, 'CLAUDE.md');

    if (!existsSync(templatePath)) {
        return;
    }

    try {
        let content = readFileSync(templatePath, 'utf-8');

        // Prepare data
        const summary = memory.current.focus?.current_goal || 'No active focus';

        const decisions = (memory.current.decisions?.decisions || [])
            .map(d => `- **${d.what}**: ${d.why}`)
            .join('\n') || 'None recorded yet.';

        const insights = (memory.current.insights?.insights || [])
            .map(i => `- ${i.learning}`)
            .join('\n') || 'None recorded yet.';

        const gotchas = (memory.current.insights?.gotchas || [])
            .map(g => `- **${g.issue}**: ${g.solution}`)
            .join('\n') || 'None recorded yet.';

        const instructions = generateInstructions();

        // Replace placeholders
        content = content.replace(/{{PROSE_SUMMARY}}/g, summary);
        content = content.replace(/{{PROSE_DECISIONS}}/g, decisions);
        content = content.replace(/{{PROSE_INSIGHTS}}/g, insights);
        content = content.replace(/{{PROSE_GOTCHAS}}/g, gotchas);
        content = content.replace(/{{PROSE_INSTRUCTIONS}}/g, instructions);

        // Add injection notice
        const notice = `\n\n> [!NOTE]\n> This file is automatically generated from \`CLAUDE.md.template\` by \`prose\`.\n> Last updated: ${new Date().toLocaleString()}\n`;

        writeFileSync(targetPath, content + notice);
        console.log(`📝 Updated CLAUDE.md from template`);
    } catch (error: any) {
        console.error(`⚠️  Failed to inject memory into CLAUDE.md: ${error.message}`);
    }
}
