import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import type { ProjectMemory } from './memory.js';

/**
 * Inject project memory into CLAUDE.md if a template exists
 */
export function injectMemory(rootPath: string, memory: ProjectMemory): void {
    const templatePath = join(rootPath, 'CLAUDE.md.template');
    const targetPath = join(rootPath, 'CLAUDE.md');

    if (!existsSync(templatePath)) {
        return;
    }

    try {
        let content = readFileSync(templatePath, 'utf-8');

        // Prepare data
        const summary = memory.current.focus?.current_goal || 'No active focus';

        const decisions = (memory.current.decisions?.decisions || [])
            .map(d => `- **${d.what}**: ${d.why}`)
            .join('\n') || 'None recorded yet.';

        const insights = (memory.current.insights?.insights || [])
            .map(i => `- ${i.learning}`)
            .join('\n') || 'None recorded yet.';

        const gotchas = (memory.current.insights?.gotchas || [])
            .map(g => `- **${g.issue}**: ${g.solution}`)
            .join('\n') || 'None recorded yet.';

        // Replace placeholders
        content = content.replace(/{{PROSE_SUMMARY}}/g, summary);
        content = content.replace(/{{PROSE_DECISIONS}}/g, decisions);
        content = content.replace(/{{PROSE_INSIGHTS}}/g, insights);
        content = content.replace(/{{PROSE_GOTCHAS}}/g, gotchas);

        // Add injection notice
        const notice = `\n\n> [!NOTE]\n> This file is automatically generated from \`CLAUDE.md.template\` by \`claude-prose\`.\n> Last updated: ${new Date().toLocaleString()}\n`;

        writeFileSync(targetPath, content + notice);
        console.log(`📝 Updated CLAUDE.md from template`);
    } catch (error: any) {
        console.error(`⚠️  Failed to inject memory into CLAUDE.md: ${error.message}`);
    }
}
